### ISSUE TITLE
Add support for Bearer Authorization

### ISSUE THREAD

**Issue by mcintyre94** [NotionX/react-notion-x#76] opened 2021-05-30 16:19 UTC
The official Notion API allows integrations to request Notion data using a Bearer token (which may be the integration token, or an access token from Oauth). This must be passed an an authorization header: `Authorization: Bearer {MY_NOTION_TOKEN}`. 
It looks like currently only an auth token is supported, which is passed as a cookie. It'd be great if `react-notion-x` could support the Bearer header as well, so that it can be used to request page data for a Notion integration. 

Relevant docs: https://developers.notion.com/docs/authorization#overview 

Edit: it looks like this is more work than just switching auth, different URLs altogether. Might be a dupe of https://github.com/NotionX/react-notion-x/issues/66

**Comment by AndrejGajdos** [comment] 2021-06-01 13:48
I came across the same issue and I thought `authToken` is actually Bearer token. Thanks @mcintyre94 for pointing this out.

**Comment by transitive-bullshit** [comment] 2022-03-26 09:06
Thanks for pointing this out @mcintyre94.

As far as I'm aware, we can't use the bearer authorization with Notion's unofficial API, only the official one.

For supporting the official API, see #66 and #228.

Cosing this as a dupe of #66

Thanks!

**Closed by transitive-bullshit** 2022-03-26 09:06 UTC
