### ISSUE TITLE
Support for @notionhq/client

### ISSUE THREAD

**Issue by dashkevych** [NotionX/react-notion-x#173] opened 2021-12-07 17:05 UTC
Does this renderer work with [@notionhq/client](https://www.npmjs.com/package/@notionhq/client)? 

If yes, what would be a correct way of using `react-notion-x` with `@notionhq/client` and private pages? A simple example of rendering blocks would be very helpful.

**Comment by normdoow** [comment] 2021-12-13 21:14
Don't beleive there is any easy way to make this work currently. react-notion-x has it's own client thats used behind the scenes.

**Comment by enpitsuLin** [comment] 2022-01-15 15:00
actually notion-client use api that [notion](notion.so) itself base on (you can see it in browser DevTools' network panel),but @notionhq/client is official RESTFUL wrapper.
so this  cause their data structures completely different that work is very difficult.
___
if you just want more official , there are two way:
1. [notion-page-to-html](https://github.com/asnunes/notion-page-to-html) 
2. [notion-to-md](https://github.com/souvikinator/notion-to-md) and use Markdown parser to render html

**Comment by ycjcl868** [comment] 2022-01-21 01:27
+1

**Comment by transitive-bullshit** [comment] 2022-03-25 11:52
Closing as a duplicate of #66.

See #228 for a discussion of how to move forward on this.

**Closed by transitive-bullshit** 2022-03-25 11:52 UTC

**Comment by transitive-bullshit** [comment] 2022-03-25 11:53
> Don't beleive there is any easy way to make this work currently. react-notion-x has it's own client thats used behind the scenes.

Just to be clear, `react-notion-x` uses the same API and data format that the notion apps all use. It should be possible to create a straightforward mapper between notion's public API data format and their private one.
