### ISSUE TITLE
Overlay from react-notion-x prevents interaction with the page

### ISSUE THREAD

**Issue by d-ivashchuk** [NotionX/react-notion-x#135] opened 2021-09-29 06:29 UTC
For some reason when using `react-notion-x` renderer I have this overlay appearing(multiplied by number of instances of `Renderer` I used, so if I have 5 of them I will have 5 overlays of such kind). Does anyone have a clue how I could get rid of it properly - I don't need the image zoom in functionality. Still this is a bug most probably, right?

<img width="961" alt="Screenshot 2021-09-29 at 08 27 31" src="https://user-images.githubusercontent.com/29632358/135214652-fb0bfda5-b113-4355-8184-af2804700381.png">

**Comment by yehezkielgunawan** [comment] 2021-09-29 13:21
Oh, I have the same problem with you. I only can interact with the link, nothing else. Even I can't copy and paste my own text on the page. Hope there's a solution.

**Comment by yehezkielgunawan** [comment] 2021-09-30 04:31
I've made a PR at [https://github.com/NotionX/react-notion-x/pull/137](https://github.com/NotionX/react-notion-x/pull/137). Found that there's a class `notion-viewport` with `position: fixed` that makes the overlay.

**Comment by agcty** [comment] 2021-10-12 07:22
Same issue here! Especially when using with custom layouts this is a real problem

**Comment by yehezkielgunawan** [comment] 2021-10-13 10:45
@agcty , this issue caused by `notion-viewport` with `position: fixed` at `packages/react-notion-x/src/styles.css`. So far, in my case, I used custom CSS to override the styling. You can try it for now until this issue is reproduced and fixed.

**Comment by normdoow** [comment] 2022-01-18 20:09
fixed in v4.13.4

**Closed by normdoow** 2022-01-18 20:09 UTC
